### ISSUE TITLE
WebPな画像をダウンロードしようとするとダウンロードに失敗する

### ISSUE THREAD

**Issue by pantasystem** [Kinoshita0623/MisskeyAndroidClient#1812]
# 概要
画像の種類によってはwebpな画像が存在するため
画像としてそのままダウンロードするとエラーが発生しています。
```
download error
                                                                                                    java.lang.IllegalArgumentException: MIME type application/octet-stream cannot be inserted into content://media/external_primary/images/media; expected MIME type under image/*
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
                                                                                                    	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
                                                                                                    	at android.content.ContentResolver.insert(ContentResolver.java:2193)
                                                                                                    	at android.content.ContentResolver.insert(ContentResolver.java:2155)
                                                                                                    	at net.pantasystem.milktea.media.RemoteFileDownloadWorkManager.doWork(RemoteFileDownloadWorkManager.kt:106)
                                                                                                    	at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:68)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**Comment by pantasystem** [comment]
Bitmapに変換してpngで保存することによって一時的に解決した。
