### ISSUE TITLE
削除して編集しようとするとクラッシュする

### ISSUE THREAD

**Issue by Kinoshita0623** [Kinoshita0623/MisskeyAndroidClient#204]
```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = jp.panta.misskeyandroidclient.model.notes.NoteRelation$Normal)
	at android.os.Parcel.writeSerializable(Parcel.java:1836)
	at android.os.Parcel.writeValue(Parcel.java:1783)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:931)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1593)
	at android.os.Bundle.writeToParcel(Bundle.java:1253)
	at android.os.Parcel.writeBundle(Parcel.java:1000)
	at android.content.Intent.writeToParcel(Intent.java:10520)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3945)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5258)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at android.app.Activity.startActivityForResult(Activity.java:5216)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
	at android.app.Activity.startActivity(Activity.java:5587)
	at android.app.Activity.startActivity(Activity.java:5555)
	at jp.panta.misskeyandroidclient.view.notes.ActionNoteHandler.openNoteEditor$lambda-14(ActionNoteHandler.kt:110)
	at jp.panta.misskeyandroidclient.view.notes.ActionNoteHandler.lambda$2DM6B2KSiU3T_CQBbSD03zhP5Y4(Unknown Source:0)
	at jp.panta.misskeyandroidclient.view.notes.-$$Lambda$ActionNoteHandler$2DM6B2KSiU3T_CQBbSD03zhP5Y4.onChanged(Unknown Source:4)
	at jp.panta.misskeyandroidclient.util.eventbus.EventBus.handleEvent(EventBus.kt:64)
	at jp.panta.misskeyandroidclient.util.eventbus.EventBus.setEvent(EventBus.kt:21)
	at jp.panta.misskeyandroidclient.viewmodel.notes.NotesViewModel$removeAndEditNote$1$2$1.invokeSuspend(NotesViewModel.kt:286)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.io.NotSerializableException: kotlinx.datetime.Instant
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:1831)
	... 29 more

```

**Comment by Kinoshita0623** [comment]
# 原因
kotlinx datetimeがSerializableを実装していないのが原因
# 解決策
削除せずにIdで渡す
投稿成功時に削除処理を実施するようにする。

**Comment by Kinoshita0623** [comment]
# 解決策2
即座に削除されないと不満を持つユーザーがいる可能性があるので
下書き->削除の順番で実行する
