### ISSUE TITLE
Drive画面でSwipeRefreshしようとするとクラッシュする

### ISSUE THREAD

**Issue by Kinoshita0623** [Kinoshita0623/MisskeyAndroidClient#213]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jp.panta.misskeyandroidclient, PID: 10958
    java.lang.IllegalArgumentException: Layout size for current item is 0
        at com.google.accompanist.pager.PagerState$scrollableState$1.invoke(PagerState.kt:179)
        at com.google.accompanist.pager.PagerState$scrollableState$1.invoke(PagerState.kt:175)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:134)
        at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-Tj5QQXo(Scrollable.kt:195)
        at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$outerScopeScroll$1.invoke(Scrollable.kt:233)
        at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$outerScopeScroll$1.invoke(Scrollable.kt:232)
        at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$scope$1.scrollBy(Scrollable.kt:237)
        at com.google.accompanist.pager.PagerDefaults$defaultPagerFlingConfig$1$1$performFling$2.invoke(Pager.kt:113)
        at com.google.accompanist.pager.PagerDefaults$defaultPagerFlingConfig$1$1$performFling$2.invoke(Pager.kt:113)
        at com.google.accompanist.pager.PagerState$fling$3.invoke(PagerState.kt:602)
        at com.google.accompanist.pager.PagerState$fling$3.invoke(PagerState.kt:601)
        at androidx.compose.animation.core.SuspendAnimationKt$animate$3.invoke(SuspendAnimation.kt:110)
        at androidx.compose.animation.core.SuspendAnimationKt$animate$3.invoke(SuspendAnimation.kt:109)
        at androidx.compose.animation.core.SuspendAnimationKt.doAnimationFrame(SuspendAnimation.kt:321)
        at androidx.compose.animation.core.SuspendAnimationKt.access$doAnimationFrame(SuspendAnimation.kt:1)
        at androidx.compose.animation.core.SuspendAnimationKt$animate$6.invoke(SuspendAnimation.kt:241)
        at androidx.compose.animation.core.SuspendAnimationKt$animate$6.invoke(SuspendAnimation.kt:229)
        at androidx.compose.animation.core.SuspendAnimationKt$callWithFrameNanos$2.invoke(SuspendAnimation.kt:287)
        at androidx.compose.animation.core.SuspendAnimationKt$callWithFrameNanos$2.invoke(SuspendAnimation.kt:286)
        at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
        at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:423)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:416)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Kinoshita0623** [comment]
HorizontalPagerを無効化して一時的に対応

**Comment by Kinoshita0623** [comment]
原因は内側のレイアウトのサイズが指定されておらず
サイズが0以下になってしまうのが原因だった。
